name: "Kitchen Manager"
version: "0.0.1"
slug: "kitchen_manager"
description: "Modern Kitchen Management: Shopping, Inventory, Recipes"
url: "https://github.com/robinheinrich/kitchen_manager"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - "config:rw"
  - "share:rw"
options: {}
schema: {}
ports:
  8000/tcp: 8000
ingress: true
ingress_port: 8000
ingress_entry: /
panel_icon: "mdi:fridge-outline"
